# -*- mode: python ; coding: utf-8 -*-

import sys
import os
from PyInstaller.utils.hooks import collect_data_files

block_cipher = None

# Raccogli automaticamente tutti i file di dati di Flet (incluso icons.json)
flet_datas = collect_data_files('flet')

a = Analysis(
    ['main.py'],
    pathex=['.', 'src'],
    binaries=[],
    datas=[
        ('src/leggimi', 'leggimi'),
    ] + flet_datas,
    hiddenimports=[
        # Core
        'flet',
        'flet_audio',
        'flet_desktop',
        'miniaudio',
        'edge_tts',
        'pydub',
        'fitz',
        'fitz.utils',
        'openai',
        'openai.lib',
        'openai.types',
        'pydantic',
        'pydantic_core',
        'httpx',
        'httpcore',
        'h11',
        'certifi',
        'urllib3',
        'requests',
        'asyncio',
        'aiohttp',
        'aiohappyeyeballs',
        'aiosignal',
        'attrs',
        'charset_normalizer',
        'yarl',
        'multidict',
        'propcache',
        'frozenlist',
        'msgpack',
        # Package leggimi
        'leggimi',
        'leggimi.models',
        'leggimi.models.models',
        'leggimi.ui',
        'leggimi.ui.ui_components',
        'leggimi.ui.playback_lines',
        'leggimi.ui.ui_theme',
        'leggimi.ui.ui_config',
        'leggimi.errors',
        'leggimi.audio_player',
        'leggimi.pipeline',
        'leggimi.extractor',
        'leggimi.segmenter',
        'leggimi.scriptgen',
        'leggimi.tts',
        'leggimi.cache',
        'leggimi.llm_client',
        'leggimi.config',
        'leggimi.prompts',
        # Edge TTS
        'edge_tts.voices',
        'edge_tts.util',
        'edge_tts.communicate',
        # PyMuPDF
        'pymupdf',
        'pymupdf.utils',
        # CFFI
        '_cffi_backend',
        'cffi',
        'cffi.api',
        'cffi.cparser',
        'cffi.error',
        'cffi.model',
        'cffi.pkgconfig',
        'cffi.recompiler',
        'cffi.vengine_cpy',
        'cffi.vengine_gen',
        # Rich (richiesto da flet-desktop)
        'rich',
        'rich.console',
        'rich.markup',
        'rich.segment',
        'rich.style',
        'rich.text',
        'rich.color',
        'rich.color_triplet',
        'rich.palette',
        'rich.cells',
        'rich.ansi',
        'rich.screen',
        'rich.highlighter',
        'rich.theme',
        'rich.terminal_theme',
        # Altre dipendenze
        'dotenv',
        'python_dotenv',
        'jinja2',
        'markupsafe',
        'click',
        'packaging',
        'typing_extensions',
        'typing_inspection',
        'annotated_types',
        'anyio',
        'sniffio',
        'distro',
        'jiter',
        'multiprocessing',
        'pycparser',
        'pycparser.ply',
        'pycparser.ply.yacc',
        'pycparser.ply.lex',
        # Flet internals
        'flet.controls',
        'flet.controls.material',
        'flet.controls.cupertino',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'numpy',
        'pandas',
        'matplotlib',
        'scipy',
        'IPython',
        'notebook',
        'jupyter',
        'pytest',
        'mkdocs',
        'mkdocs_material',
        'pygments',
        'babel',
        'watchdog',
        'ghp_import',
        'mergedeep',
        'setuptools',
        'pip',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyd = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyd,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='LeggiMi',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)