site_name: LeggiMi
site_description: Trasforma PDF in audiolibri con intelligenza artificiale
site_author: TheStxfan
site_url: https://thestxfan.github.io/leggimi/
repo_url: https://github.com/TheStxfan/leggimi.git

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: slate
      primary: amber
      accent: amber

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

  - Per iniziare:
      - Getting Started: getting-started.md
      - Guida all'installazione: setup.md
      - Come eseguire: run.md
      - Ottenere una API Key: api.md

  - Guida allo sviluppo:
      - Architettura interna: internals.md
      - Struttura dei file del progetto: structure.md
      - Compilazione con PyInstaller: build.md

  - Supporto:
      - Risoluzione problemi: trobleshoot.md
      - Interfaccia utente: ui.md
